<template><div><h1 id="_1、安装docker" tabindex="-1"><a class="header-anchor" href="#_1、安装docker" aria-hidden="true">#</a> 1、安装docker</h1>
<h2 id="_1-安装gcc" tabindex="-1"><a class="header-anchor" href="#_1-安装gcc" aria-hidden="true">#</a> （1）安装Gcc</h2>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code>yum <span class="token operator">-</span>y install gcc
yum <span class="token operator">-</span>y install gcc<span class="token operator">-</span>c<span class="token operator">++</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="_2-卸载旧版本" tabindex="-1"><a class="header-anchor" href="#_2-卸载旧版本" aria-hidden="true">#</a> （2）卸载旧版本</h2>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code>yum <span class="token operator">-</span>y remove docker docker<span class="token operator">-</span>common docker<span class="token operator">-</span>selinux docker<span class="token operator">-</span>engine

yum remove
docker \
docker<span class="token operator">-</span>client \
docker<span class="token operator">-</span>client<span class="token operator">-</span>latest \
docker<span class="token operator">-</span>common \
docker<span class="token operator">-</span>latest \
docker<span class="token operator">-</span>latest<span class="token operator">-</span>logrotate \
docker<span class="token operator">-</span>logrotate \
docker<span class="token operator">-</span>engine
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="_3-设置stable镜像仓库" tabindex="-1"><a class="header-anchor" href="#_3-设置stable镜像仓库" aria-hidden="true">#</a> （3）设置stable镜像仓库</h2>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code>yum<span class="token operator">-</span>config<span class="token operator">-</span>manager <span class="token operator">--</span>add<span class="token operator">-</span>repo http<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span>mirrors<span class="token punctuation">.</span>aliyun<span class="token punctuation">.</span>com<span class="token operator">/</span>docker<span class="token operator">-</span>ce<span class="token operator">/</span>linux<span class="token operator">/</span>centos<span class="token operator">/</span>docker<span class="token operator">-</span>ce<span class="token punctuation">.</span>repo
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="_4-更新yum软件包索引" tabindex="-1"><a class="header-anchor" href="#_4-更新yum软件包索引" aria-hidden="true">#</a> （4）更新yum软件包索引</h2>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code>yum makecache <span class="token punctuation">(</span>centos <span class="token number">8</span><span class="token punctuation">)</span>
yum makecache <span class="token function">fast</span><span class="token punctuation">(</span>centos <span class="token number">7</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="_5-安装docker-ce" tabindex="-1"><a class="header-anchor" href="#_5-安装docker-ce" aria-hidden="true">#</a> （5）安装Docker CE</h2>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code>yum <span class="token operator">-</span>y install docker<span class="token operator">-</span>ce docker<span class="token operator">-</span>ce<span class="token operator">-</span>cli containerd<span class="token punctuation">.</span>io
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="_6-启动docker" tabindex="-1"><a class="header-anchor" href="#_6-启动docker" aria-hidden="true">#</a> （6）启动docker</h2>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code>启动：
systemctl start docker
设置开机自启动：
systemctl start docker
systemctl enable docker
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-text line-numbers-mode" data-ext="text"><pre v-pre class="language-text"><code>测试：
docker version
docker run hello-world
docker images
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token punctuation">[</span>root<span class="token annotation punctuation">@localhost</span> <span class="token operator">~</span><span class="token punctuation">]</span># docker version
<span class="token class-name">Client</span><span class="token operator">:</span> <span class="token class-name">Docker</span> <span class="token class-name">Engine</span> <span class="token operator">-</span> <span class="token class-name">Community</span>
 <span class="token class-name">Version</span><span class="token operator">:</span>           <span class="token number">20.10</span><span class="token number">.7</span>
 <span class="token constant">API</span> version<span class="token operator">:</span>       <span class="token number">1.41</span>
 <span class="token class-name">Go</span> version<span class="token operator">:</span>        go1<span class="token punctuation">.</span><span class="token number">13.15</span>
 <span class="token class-name">Git</span> commit<span class="token operator">:</span>        f0df350
 <span class="token class-name">Built</span><span class="token operator">:</span>             <span class="token class-name">Wed</span> <span class="token class-name">Jun</span>  <span class="token number">2</span> <span class="token number">11</span><span class="token operator">:</span><span class="token number">56</span><span class="token operator">:</span><span class="token number">24</span> <span class="token number">2021</span>
 <span class="token constant">OS</span><span class="token operator">/</span><span class="token class-name">Arch</span><span class="token operator">:</span>           linux<span class="token operator">/</span>amd64
 <span class="token class-name">Context</span><span class="token operator">:</span>           <span class="token keyword">default</span>
 <span class="token class-name">Experimental</span><span class="token operator">:</span>      <span class="token boolean">true</span>

<span class="token class-name">Server</span><span class="token operator">:</span> <span class="token class-name">Docker</span> <span class="token class-name">Engine</span> <span class="token operator">-</span> <span class="token class-name">Community</span>
 <span class="token class-name">Engine</span><span class="token operator">:</span>
  <span class="token class-name">Version</span><span class="token operator">:</span>          <span class="token number">20.10</span><span class="token number">.7</span>
  <span class="token constant">API</span> version<span class="token operator">:</span>      <span class="token number">1.41</span> <span class="token punctuation">(</span>minimum version <span class="token number">1.12</span><span class="token punctuation">)</span>
  <span class="token class-name">Go</span> version<span class="token operator">:</span>       go1<span class="token punctuation">.</span><span class="token number">13.15</span>
  <span class="token class-name">Git</span> commit<span class="token operator">:</span>       b0f5bc3
  <span class="token class-name">Built</span><span class="token operator">:</span>            <span class="token class-name">Wed</span> <span class="token class-name">Jun</span>  <span class="token number">2</span> <span class="token number">11</span><span class="token operator">:</span><span class="token number">54</span><span class="token operator">:</span><span class="token number">48</span> <span class="token number">2021</span>
  <span class="token constant">OS</span><span class="token operator">/</span><span class="token class-name">Arch</span><span class="token operator">:</span>          linux<span class="token operator">/</span>amd64
  <span class="token class-name">Experimental</span><span class="token operator">:</span>     <span class="token boolean">false</span>
 containerd<span class="token operator">:</span>
  <span class="token class-name">Version</span><span class="token operator">:</span>          <span class="token number">1.4</span><span class="token number">.6</span>
  <span class="token class-name">GitCommit</span><span class="token operator">:</span>        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc<span class="token operator">:</span>
  <span class="token class-name">Version</span><span class="token operator">:</span>          <span class="token number">1.0</span><span class="token number">.0</span><span class="token operator">-</span>rc95
  <span class="token class-name">GitCommit</span><span class="token operator">:</span>        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker<span class="token operator">-</span>init<span class="token operator">:</span>
  <span class="token class-name">Version</span><span class="token operator">:</span>          <span class="token number">0.19</span><span class="token number">.0</span>
  <span class="token class-name">GitCommit</span><span class="token operator">:</span>        de40ad0
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="_2、开启2375端口-提供外部访问docker" tabindex="-1"><a class="header-anchor" href="#_2、开启2375端口-提供外部访问docker" aria-hidden="true">#</a> 2、开启2375端口，提供外部访问docker</h2>
<p>在docker配置文件</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token class-name">ExecStart</span><span class="token operator">=</span><span class="token operator">/</span>usr<span class="token operator">/</span>bin<span class="token operator">/</span>dockerd <span class="token operator">-</span><span class="token class-name">H</span> fd<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span> <span class="token operator">--</span>containerd<span class="token operator">=</span><span class="token operator">/</span>run<span class="token operator">/</span>containerd<span class="token operator">/</span>containerd<span class="token punctuation">.</span>sock 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>之后加上</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token operator">-</span><span class="token class-name">H</span> tcp<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">0.0</span><span class="token number">.0</span><span class="token number">.0</span><span class="token operator">:</span><span class="token number">2375</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>具体操作为</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code>vim <span class="token operator">/</span>usr<span class="token operator">/</span>lib<span class="token operator">/</span>systemd<span class="token operator">/</span>system<span class="token operator">/</span>docker<span class="token punctuation">.</span>service
<span class="token class-name">ExecStart</span><span class="token operator">=</span><span class="token operator">/</span>usr<span class="token operator">/</span>bin<span class="token operator">/</span>dockerd <span class="token operator">-</span><span class="token class-name">H</span> fd<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span> <span class="token operator">--</span>containerd<span class="token operator">=</span><span class="token operator">/</span>run<span class="token operator">/</span>containerd<span class="token operator">/</span>containerd<span class="token punctuation">.</span>sock <span class="token operator">-</span><span class="token class-name">H</span> tcp<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">0.0</span><span class="token number">.0</span><span class="token number">.0</span><span class="token operator">:</span><span class="token number">2375</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-text line-numbers-mode" data-ext="text"><pre v-pre class="language-text"><code>systemctl restart docker
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>然后linux防火墙开启2375端口</p>
<h1 id="_3、使用idea连接docker服务" tabindex="-1"><a class="header-anchor" href="#_3、使用idea连接docker服务" aria-hidden="true">#</a> 3、使用idea连接docker服务</h1>
<p>idea安装docker服务</p>
<p>idea -----&gt; setting -----&gt; Plugins -----&gt; Marketplace -----&gt; docker install</p>
<figure><img src="/assets/images/image-20210718193618402.png" alt="image-20210718193618402" tabindex="0" loading="lazy"><figcaption>image-20210718193618402</figcaption></figure>
<p>idea -----&gt; setting -----&gt; Build, Execution, Deployment - Docker -----&gt; TCP socket -----&gt; Engine API URL 键入 tcp://192.168.2.195:2375</p>
<figure><img src="/assets/images/image-20210718193314796.png" alt="image-20210718193314796" tabindex="0" loading="lazy"><figcaption>image-20210718193314796</figcaption></figure>
<h1 id="_4、配置" tabindex="-1"><a class="header-anchor" href="#_4、配置" aria-hidden="true">#</a> 4、配置</h1>
<p>pom和Dockerfile在同一目录下：</p>
<p>pom中添加：</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token operator">&lt;</span><span class="token operator">!</span><span class="token operator">--</span>docke maven编译插件<span class="token operator">--</span><span class="token operator">></span>
            <span class="token generics"><span class="token punctuation">&lt;</span>plugin<span class="token punctuation">></span></span>
                <span class="token generics"><span class="token punctuation">&lt;</span>groupId<span class="token punctuation">></span></span>com<span class="token punctuation">.</span>spotify<span class="token operator">&lt;</span><span class="token operator">/</span>groupId<span class="token operator">></span>
                <span class="token generics"><span class="token punctuation">&lt;</span>artifactId<span class="token punctuation">></span></span>dockerfile<span class="token operator">-</span>maven<span class="token operator">-</span>plugin<span class="token operator">&lt;</span><span class="token operator">/</span>artifactId<span class="token operator">></span>
                <span class="token generics"><span class="token punctuation">&lt;</span>version<span class="token punctuation">></span></span><span class="token number">1.4</span><span class="token number">.9</span><span class="token operator">&lt;</span><span class="token operator">/</span>version<span class="token operator">></span>
                <span class="token generics"><span class="token punctuation">&lt;</span>configuration<span class="token punctuation">></span></span>
                    <span class="token generics"><span class="token punctuation">&lt;</span>repository<span class="token punctuation">></span></span>$<span class="token punctuation">{</span>docker<span class="token punctuation">.</span>image<span class="token punctuation">.</span>prefix<span class="token punctuation">}</span><span class="token operator">/</span>$<span class="token punctuation">{</span>project<span class="token punctuation">.</span>artifactId<span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>repository<span class="token operator">></span>
                    <span class="token generics"><span class="token punctuation">&lt;</span>buildArgs<span class="token punctuation">></span></span>
                        <span class="token generics"><span class="token punctuation">&lt;</span>JAR_FILE<span class="token punctuation">></span></span>target<span class="token operator">/</span>$<span class="token punctuation">{</span>project<span class="token punctuation">.</span>build<span class="token punctuation">.</span>finalName<span class="token punctuation">}</span><span class="token punctuation">.</span>jar<span class="token operator">&lt;</span><span class="token operator">/</span><span class="token constant">JAR_FILE</span><span class="token operator">></span>
                    <span class="token operator">&lt;</span><span class="token operator">/</span>buildArgs<span class="token operator">></span>
                <span class="token operator">&lt;</span><span class="token operator">/</span>configuration<span class="token operator">></span>
            <span class="token operator">&lt;</span><span class="token operator">/</span>plugin<span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Dockerfile：</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code># docker中的镜像
<span class="token constant">FROM</span> openjdk<span class="token operator">:</span><span class="token number">8</span><span class="token operator">-</span>jdk<span class="token operator">-</span>alpine
<span class="token constant">MAINTAINER</span> zhengtianqi <span class="token operator">&lt;</span><span class="token number">270490096</span><span class="token annotation punctuation">@qq.com</span><span class="token operator">></span>
<span class="token constant">VOLUME</span> <span class="token operator">/</span>tmp
<span class="token constant">ADD</span> target<span class="token operator">/</span>springcloud<span class="token operator">-</span>ztq<span class="token punctuation">.</span>jar app<span class="token punctuation">.</span>jar
<span class="token constant">EXPOSE</span> <span class="token number">8080</span>
<span class="token constant">ENTRYPOINT</span> <span class="token punctuation">[</span><span class="token string">"java"</span><span class="token punctuation">,</span><span class="token string">"-jar"</span><span class="token punctuation">,</span><span class="token string">"app.jar"</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>执行的命令：</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code>windows进行打包并上传镜像：
<span class="token constant">DOCKER_HOST</span><span class="token operator">=</span>tcp<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">92.168</span><span class="token number">.2</span><span class="token number">.195</span><span class="token operator">:</span><span class="token number">2375</span> mvn clean <span class="token keyword">package</span> <span class="token namespace">dockerfile</span><span class="token operator">:</span>build
linux查看镜像并运行：

<span class="token punctuation">[</span>root<span class="token annotation punctuation">@localhost</span> <span class="token operator">~</span><span class="token punctuation">]</span># docker images
<span class="token constant">REPOSITORY</span>                      <span class="token constant">TAG</span>            <span class="token constant">IMAGE</span> <span class="token constant">ID</span>       <span class="token constant">CREATED</span>       <span class="token constant">SIZE</span>
springboot<span class="token operator">-</span>ztq<span class="token operator">/</span>springboot<span class="token operator">-</span>ztq   latest         <span class="token number">825d</span><span class="token number">7f</span><span class="token number">3967</span>cf   <span class="token number">3</span> hours ago   <span class="token number">221</span><span class="token constant">MB</span>
openjdk                         <span class="token number">8</span><span class="token operator">-</span>jdk<span class="token operator">-</span>alpine   a3562aa0b991   <span class="token number">2</span> years ago   <span class="token number">105</span><span class="token constant">MB</span>

<span class="token punctuation">[</span>root<span class="token annotation punctuation">@localhost</span> <span class="token operator">~</span><span class="token punctuation">]</span># docker run <span class="token operator">-</span>d <span class="token operator">-</span>p <span class="token number">8080</span><span class="token operator">:</span><span class="token number">8080</span> <span class="token operator">-</span>i <span class="token number">825d</span><span class="token number">7f</span><span class="token number">3967</span>cf
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


