<template><div><h1 id="一、加载数据" tabindex="-1"><a class="header-anchor" href="#一、加载数据" aria-hidden="true">#</a> 一、加载数据</h1>
<p>Hive 没有行级别的数据插入、数据更新和删除操作，那么网表中装载数据的唯一途径就是使用一种 “ 大量 ” 的数据装载操作。或者通过其他方式仅仅将文件写入到正确的目录下。</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// OVERWRITE关键字换成INTO关键字的话，Hive将会以追加的方式写入数据而不会覆盖之前已经存在的内容</span>
<span class="token constant">LOAD</span> <span class="token constant">DATA</span> <span class="token constant">LOCAL</span> <span class="token constant">INPATH</span> '$<span class="token punctuation">{</span>env<span class="token operator">:</span><span class="token constant">HOME</span><span class="token punctuation">}</span><span class="token operator">/</span>california<span class="token operator">-</span>employees'  
<span class="token constant">OVERWRITE</span> <span class="token constant">INTO</span> <span class="token constant">TABLE</span> employees
<span class="token comment">// 非分区表省略此行</span>
<span class="token constant">PARTITION</span> <span class="token punctuation">(</span>country <span class="token operator">=</span> <span class="token char">'US'</span><span class="token punctuation">,</span> state <span class="token operator">=</span> <span class="token char">'CA'</span><span class="token punctuation">)</span>  
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>​		如果分区目录不存在的话，会先创建分区目录，然后再将数据拷贝到该目录下。</p>
<h1 id="二、设置分区" tabindex="-1"><a class="header-anchor" href="#二、设置分区" aria-hidden="true">#</a> 二、设置分区</h1>
<figure><img src="/assets/images/hive-partition.png" alt="image-20200119115936949" tabindex="0" loading="lazy"><figcaption>image-20200119115936949</figcaption></figure>
<p>上表为动态分区属性，如果不小心按照秒分区，每秒建立一个分区，则十分浪费资源，设置hive.exec.max.dynamic.partitions可以创建最大动态分区个数，如果超过这个值就会抛出一个致命错误。</p>
<p>设置分区的方式</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code>hive<span class="token operator">></span> set hive<span class="token punctuation">.</span>exec<span class="token punctuation">.</span>dynamic<span class="token punctuation">.</span>partition<span class="token operator">=</span><span class="token boolean">true</span><span class="token punctuation">;</span>
hive<span class="token operator">></span> set hive<span class="token punctuation">.</span>exec<span class="token punctuation">.</span>dynamic<span class="token punctuation">.</span>partition<span class="token punctuation">.</span>mode<span class="token operator">=</span>nonstrict<span class="token punctuation">;</span>
hive<span class="token operator">></span> set hive<span class="token punctuation">.</span>exec<span class="token punctuation">.</span>max<span class="token punctuation">.</span>dynamic<span class="token punctuation">.</span>partitions<span class="token punctuation">.</span>pernode<span class="token operator">=</span><span class="token number">1000</span><span class="token punctuation">;</span>
hive<span class="token operator">></span> <span class="token constant">INSERT</span> <span class="token constant">OVERWRITE</span> <span class="token constant">TABLE</span> employees
	<span class="token operator">></span> <span class="token constant">PARTITION</span> <span class="token punctuation">(</span>country<span class="token punctuation">,</span> state<span class="token punctuation">)</span>
	<span class="token operator">></span> <span class="token constant">PARTITION</span> <span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">,</span> se<span class="token punctuation">.</span>cty<span class="token punctuation">,</span> se<span class="token punctuation">.</span>st
	<span class="token operator">></span> <span class="token constant">FROM</span> staged_employees se<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h1 id="三、单个查询语句中创建表并加载数据" tabindex="-1"><a class="header-anchor" href="#三、单个查询语句中创建表并加载数据" aria-hidden="true">#</a> 三、单个查询语句中创建表并加载数据</h1>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token constant">CREATE</span> <span class="token constant">TABLE</span> ca_employees
<span class="token constant">AS</span> <span class="token class-name">SELECT</span> name<span class="token punctuation">,</span> salary<span class="token punctuation">,</span> address
<span class="token constant">FROM</span> employees <span class="token constant">WHERE</span> se<span class="token punctuation">.</span>state <span class="token operator">=</span> <span class="token char">'CA'</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h1 id="四、导出数据" tabindex="-1"><a class="header-anchor" href="#四、导出数据" aria-hidden="true">#</a> 四、导出数据</h1>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">//（1）直接拷贝文件夹</span>
hadoop fs <span class="token operator">-</span>cp source_path <span class="token constant">DIRECTORY</span> '<span class="token operator">/</span>tmp<span class="token operator">/</span>ca_employees'
    
<span class="token comment">//（2）或者用INSERT ... DICTORY ...,</span>
<span class="token comment">// 也可以写成全路径 hdfs://master-server/tmp/ca_employees</span>
<span class="token constant">INSERT</span> <span class="token constant">OVERWRITE</span> <span class="token constant">LOCAL</span> <span class="token constant">DIRECTORY</span> '<span class="token operator">/</span>tmp<span class="token operator">/</span>ca_employees' 
<span class="token class-name">SELECT</span> name<span class="token punctuation">,</span> salary<span class="token punctuation">,</span> adress 
<span class="token constant">FROM</span> employees 
<span class="token constant">WHERE</span> se<span class="token punctuation">.</span>state <span class="token operator">=</span> <span class="token char">'CA'</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h1 id="五、hiveql-查询" tabindex="-1"><a class="header-anchor" href="#五、hiveql-查询" aria-hidden="true">#</a> 五、HiveQL 查询</h1>
<p>SELECT是SQL中的映射算子，指定了要保存的列以输出函数需要调用的一个或多个列；</p>
<p>FROM子句标识了从哪个表、试图或嵌套查询中选择记录。</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// 查询ARRAY的第一个元素</span>
<span class="token class-name">SELECT</span> name<span class="token punctuation">,</span> subordinates<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span> <span class="token class-name">FROM</span> employees<span class="token punctuation">;</span>
<span class="token comment">// 查询键值</span>
<span class="token class-name">SELECT</span> name<span class="token punctuation">,</span> deductions<span class="token punctuation">[</span><span class="token string">"State Taxes"</span><span class="token punctuation">]</span> <span class="token class-name">FROM</span> employees<span class="token punctuation">;</span>
<span class="token comment">// 查询一个元素，也可以用 ‘点’</span>
<span class="token class-name">SELECT</span> name<span class="token punctuation">,</span> address<span class="token punctuation">.</span>city <span class="token class-name">FROM</span> employees<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>（1）Hive支持的算数运算符</p>
<figure><img src="/assets/images/hive-算数运算符.png" alt="image-20200119143105348" tabindex="0" loading="lazy"><figcaption>image-20200119143105348</figcaption></figure>
<p>（2）Hive 内置数学函数</p>
<figure><img src="/assets/images/hive-数学函数.png" alt="image-20200119143246489" tabindex="0" loading="lazy"><figcaption>image-20200119143246489</figcaption></figure>
<figure><img src="/assets/images/hive运算1.png" alt="image-20200119143332168" tabindex="0" loading="lazy"><figcaption>image-20200119143332168</figcaption></figure>
<figure><img src="/assets/images/Hive-运算2.png" alt="image-20200119143405105" tabindex="0" loading="lazy"><figcaption>image-20200119143405105</figcaption></figure>
<figure><img src="/assets/images/hive-运算3.png" alt="image-20200119143501626" tabindex="0" loading="lazy"><figcaption>image-20200119143501626</figcaption></figure>
<p>（3）Hive聚合函数</p>
<p>最有名的是count avg</p>
<figure><img src="/assets/images/hive-聚合1.png" alt="image-20200119143648157" tabindex="0" loading="lazy"><figcaption>image-20200119143648157</figcaption></figure>
<figure><img src="/assets/images/hive-聚合2.png" alt="image-20200119143701027" tabindex="0" loading="lazy"><figcaption>image-20200119143701027</figcaption></figure>
<figure><img src="/assets/images/hive-聚合3.png" alt="image-20200119143709165" tabindex="0" loading="lazy"><figcaption>image-20200119143709165</figcaption></figure>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// 下边设置可以调高聚合的性能,这个设置会触发map阶段进行“顶级”聚合过秤，非顶级将会在执行一个GROUP BY后进行，不过这个设置会需要更多的内存。</span>
hive<span class="token operator">></span> <span class="token constant">SET</span> hive<span class="token punctuation">.</span>map<span class="token punctuation">.</span>aggr<span class="token operator">=</span><span class="token boolean">true</span><span class="token punctuation">;</span>   
hive<span class="token operator">></span> <span class="token class-name">SELECT</span> <span class="token function">count</span><span class="token punctuation">(</span><span class="token operator">*</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token function">avg</span><span class="token punctuation">(</span>salary<span class="token punctuation">)</span> <span class="token class-name">FROM</span> employees<span class="token punctuation">;</span>

<span class="token comment">// 多个函数排重后的孤僻交易码个数</span>
hive<span class="token operator">></span> <span class="token class-name">SELECT</span> <span class="token function">count</span><span class="token punctuation">(</span><span class="token class-name">DISTINCT</span> symbol<span class="token punctuation">)</span> <span class="token class-name">FROM</span> stocks<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h1 id="六、表生成函数" tabindex="-1"><a class="header-anchor" href="#六、表生成函数" aria-hidden="true">#</a> 六、表生成函数</h1>
<p>与聚合函数“相反的”一类函数就是表生成函数，其可以将单列扩展成多列或者多行。例如 AS 语句</p>
<p>例子：</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token class-name">SELECT</span> <span class="token function">parse_url_tuple</span><span class="token punctuation">(</span>url<span class="token punctuation">,</span> <span class="token char">'HOST'</span><span class="token punctuation">,</span> <span class="token char">'PATH'</span><span class="token punctuation">,</span> <span class="token char">'QUERY'</span><span class="token punctuation">)</span> <span class="token constant">AS</span> <span class="token punctuation">(</span>host<span class="token punctuation">,</span> path<span class="token punctuation">,</span> query<span class="token punctuation">)</span> <span class="token class-name">FROM</span> url_table<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="/assets/images/hive-表生成函数.png" alt="image-20200119145321380" tabindex="0" loading="lazy"><figcaption>image-20200119145321380</figcaption></figure>
<h1 id="七、其他内置函数" tabindex="-1"><a class="header-anchor" href="#七、其他内置函数" aria-hidden="true">#</a> 七、其他内置函数</h1>
<p>有很多，关于时间的和关于字符串的。</p>
<h1 id="八、limit-句式" tabindex="-1"><a class="header-anchor" href="#八、limit-句式" aria-hidden="true">#</a> 八、LIMIT 句式</h1>
<p>LIMIT子句勇于限制返回的行数。</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// 下面只返回两行</span>
hive<span class="token operator">></span> <span class="token class-name">SELECT</span> <span class="token function">upper</span><span class="token punctuation">(</span>name<span class="token punctuation">)</span><span class="token punctuation">,</span> salary<span class="token punctuation">,</span> deductions<span class="token punctuation">[</span><span class="token string">"Federal Taxes"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
<span class="token operator">></span> <span class="token function">round</span><span class="token punctuation">(</span>salary <span class="token operator">*</span> <span class="token punctuation">(</span><span class="token number">1</span> <span class="token operator">-</span> deductions<span class="token punctuation">[</span><span class="token string">"Federal Taxes"</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token constant">FROM</span> employees 
<span class="token operator">></span> <span class="token class-name">LIMIT</span> <span class="token number">2</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h1 id="九、case-when-then句式" tabindex="-1"><a class="header-anchor" href="#九、case-when-then句式" aria-hidden="true">#</a> 九、CASE ... WHEN ... THEN句式</h1>
<p>和if条件语句类似，用于处理单个列的查询结果。</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code>hive<span class="token operator">></span> <span class="token class-name">SELECT</span> name<span class="token punctuation">,</span> salary<span class="token punctuation">,</span>
<span class="token operator">></span> <span class="token constant">CASE</span>
<span class="token operator">></span> <span class="token constant">WHEN</span> salary  <span class="token operator">&lt;</span>  <span class="token number">50000.0</span> <span class="token constant">THEN</span> <span class="token char">'low'</span>
<span class="token operator">></span> <span class="token constant">WHEN</span> salary  <span class="token operator">>=</span>  <span class="token number">50000.0</span>  <span class="token constant">AND</span>  salary  <span class="token operator">&lt;</span> <span class="token number">70000.0</span>  <span class="token constant">THEN</span>  <span class="token char">'middle'</span>
<span class="token operator">></span> <span class="token constant">WHEN</span>  salary  <span class="token operator">>=</span>  <span class="token number">70000.0</span> <span class="token constant">AND</span>  salary  <span class="token operator">&lt;</span>  <span class="token number">100000.0</span>  <span class="token constant">THEN</span> <span class="token char">'high'</span>
<span class="token operator">></span> <span class="token constant">ELSE</span>  'very high'
<span class="token operator">></span> <span class="token constant">END</span> <span class="token constant">AS</span> bracket <span class="token class-name">FROM</span> employees<span class="token punctuation">;</span>

<span class="token comment">//返回结果</span>
<span class="token class-name">John</span> <span class="token class-name">Doe</span>   <span class="token number">100000.0</span>  veryhigh
<span class="token class-name">Mary</span> <span class="token class-name">Smith</span> <span class="token number">80000.0</span> high
<span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h1 id="十、like和rlike" tabindex="-1"><a class="header-anchor" href="#十、like和rlike" aria-hidden="true">#</a> 十、LIKE和RLIKE</h1>
<p>RLIKE 是 Hive 功能的拓展，可以通过 Java 的正则表达式来指定匹配条件。</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// LIKE</span>
hive<span class="token operator">></span> <span class="token class-name">SELECT</span> name<span class="token punctuation">,</span> address<span class="token punctuation">.</span>street <span class="token constant">FROM</span> employees <span class="token constant">WHERE</span> address<span class="token punctuation">.</span>street <span class="token constant">LIKE</span> <span class="token char">'%Ave.'</span>
<span class="token class-name">John</span> <span class="token class-name">Doe</span>   <span class="token number">1</span>  <span class="token class-name">Michigan</span> <span class="token class-name">Ave<span class="token punctuation">.</span>
Todd</span> <span class="token class-name">Jones</span> <span class="token number">200</span> <span class="token class-name">Chicago</span> <span class="token class-name">Ave</span><span class="token punctuation">.</span>
<span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span>
    
<span class="token comment">// RLIKE  后加正则表达式</span>
<span class="token comment">//（参照Tony Stubbleine《正则表达式参考手册》、JanGoyvaerts和Tony Stubbleine（O' Reilly）所著的《正则表达式参考手册》）</span>
<span class="token comment">// '.'表示和任意的字符匹配</span>
<span class="token comment">// '*'表示重复“左边的字符串”零次到无数次</span>
<span class="token comment">// '|'表示和x或者y匹配 </span>
hive<span class="token operator">></span> <span class="token class-name">SELECT</span> name<span class="token punctuation">,</span> address<span class="token punctuation">.</span>street
    <span class="token operator">></span> <span class="token constant">FROM</span> employees <span class="token constant">WHERE</span> address<span class="token punctuation">.</span>street <span class="token constant">RLIKE</span> '<span class="token punctuation">.</span>*<span class="token punctuation">(</span><span class="token class-name">Chicago</span><span class="token operator">|</span><span class="token class-name">Ontario</span><span class="token punctuation">)</span><span class="token punctuation">.</span>*'<span class="token punctuation">;</span>
<span class="token class-name">Mary</span> <span class="token class-name">Smith</span> <span class="token number">100</span> <span class="token class-name">Ontario</span> <span class="token class-name">St<span class="token punctuation">.</span>
Todd</span> <span class="token class-name">Jones</span> <span class="token number">200</span> <span class="token class-name">Chicago</span> <span class="token class-name">Ave</span><span class="token punctuation">.</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h1 id="十一、group-by" tabindex="-1"><a class="header-anchor" href="#十一、group-by" aria-hidden="true">#</a> 十一、GROUP BY</h1>
<p>GROUP BY语句通常会和聚合函数一起使用，按照一个或者多个列对结果进行分组，然后对每个组执行聚合操作。</p>
<p>例如：</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code>hive<span class="token operator">></span> <span class="token class-name">SELECT</span> <span class="token function">year</span><span class="token punctuation">(</span>ymd<span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token function">avg</span><span class="token punctuation">(</span>price_close<span class="token punctuation">)</span> <span class="token constant">FROM</span> stocks 
    <span class="token operator">></span><span class="token class-name">WHERE</span> exchange <span class="token operator">=</span> <span class="token char">'NASDAQ'</span> <span class="token class-name">AND</span> symbol <span class="token operator">=</span> <span class="token char">'AAPL'</span> 
    <span class="token operator">></span><span class="token constant">GROUP</span> <span class="token class-name">BY</span> <span class="token function">year</span><span class="token punctuation">(</span>ymd<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token number">1984</span>   <span class="token number">25.123142341341</span>
<span class="token number">1985</span>   <span class="token number">20.123145234131</span>
<span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span>

<span class="token comment">// 有时候会用HAVING子句来补充条件查询</span>
hive<span class="token operator">></span> <span class="token class-name">SELECT</span> <span class="token function">year</span><span class="token punctuation">(</span>ymd<span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token function">avg</span><span class="token punctuation">(</span>price_close<span class="token punctuation">)</span> <span class="token constant">FROM</span> stocks 
    <span class="token operator">></span><span class="token class-name">WHERE</span> exchange <span class="token operator">=</span> <span class="token char">'NASDAQ'</span> <span class="token class-name">AND</span> symbol <span class="token operator">=</span> <span class="token char">'AAPL'</span> 
    <span class="token operator">></span><span class="token constant">GROUP</span> <span class="token class-name">BY</span> <span class="token function">year</span><span class="token punctuation">(</span>ymd<span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token operator">></span><span class="token class-name">HAVING</span> <span class="token function">avg</span><span class="token punctuation">(</span>price_close<span class="token punctuation">)</span> <span class="token operator">></span> <span class="token number">50.0</span>
<span class="token comment">// 等价于下边嵌套查询</span>
hive<span class="token operator">></span> <span class="token constant">SELECT</span> s2<span class="token punctuation">.</span>year<span class="token punctuation">,</span> s2<span class="token punctuation">.</span>avg <span class="token constant">FROM</span>
    <span class="token operator">></span><span class="token punctuation">(</span><span class="token class-name">SELECT</span> <span class="token function">year</span><span class="token punctuation">(</span>ymd<span class="token punctuation">)</span> <span class="token class-name">AS</span> year<span class="token punctuation">,</span> <span class="token function">avg</span><span class="token punctuation">(</span>price_close<span class="token punctuation">)</span> <span class="token constant">AS</span> avg <span class="token class-name">FROM</span> stocks<span class="token punctuation">)</span>
    <span class="token operator">></span><span class="token class-name">WHERE</span> exchange <span class="token operator">=</span> <span class="token char">'NASDAQ'</span> <span class="token class-name">AND</span> symbol <span class="token operator">=</span> <span class="token char">'AAPL'</span>
    <span class="token operator">></span><span class="token constant">GROUP</span> <span class="token class-name">BY</span> <span class="token function">year</span><span class="token punctuation">(</span>yml<span class="token punctuation">)</span><span class="token punctuation">)</span> s2
    <span class="token operator">></span><span class="token constant">WHERE</span> s2<span class="token punctuation">.</span>avg <span class="token operator">></span> <span class="token number">50.0</span>

<span class="token number">1987</span>    <span class="token number">53.88923482352342</span>
<span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


