<template><div><h1 id="一、类型转换" tabindex="-1"><a class="header-anchor" href="#一、类型转换" aria-hidden="true">#</a> 一、类型转换</h1>
<p>​		（1）cast() 函数，可以使用这个函数对指定的值进行显式的类型转换。</p>
<p>例如：</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// 当salary字段的值是不合法的浮点数字符串的话，Hive会返回NULL</span>
<span class="token class-name">SELECT</span> name<span class="token punctuation">,</span> salary <span class="token constant">FROM</span> employees <span class="token class-name">WHERE</span> <span class="token function">cast</span><span class="token punctuation">(</span>salary <span class="token class-name">AS</span> <span class="token constant">FLOAT</span><span class="token punctuation">)</span> <span class="token operator">&lt;</span> <span class="token number">100000.0</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>注：将浮点数转换成整数的推荐方式是round()或者floor()函数，而不是使用类型转换操作符cast</p>
<p>​		（2）类型转换 BINARY 值（hive v0.8.0）</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// 只支持将 BINARY 转换为 STRING 类型(也可以 STRING 转为 BINARY)</span>
<span class="token constant">SELECT</span> <span class="token punctuation">(</span><span class="token number">2.0</span> <span class="token operator">*</span> <span class="token function">cast</span><span class="token punctuation">(</span><span class="token function">cast</span><span class="token punctuation">(</span>b string<span class="token punctuation">)</span> as <span class="token keyword">double</span><span class="token punctuation">)</span><span class="token punctuation">)</span> from src<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h1 id="二、抽样查询" tabindex="-1"><a class="header-anchor" href="#二、抽样查询" aria-hidden="true">#</a> 二、抽样查询</h1>
<p>​		对于非常大的数据集，有时用户需要使用的是一个具有代表性的查询结果而不是全部结果。Hive可以通过对表进行分桶抽样来满足这个需求。</p>
<p>例如：</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token comment">// 假设 numbers 表只有 number 字段，其值是 1 到 10</span>
<span class="token comment">// 可以利用 rand() 函数进行抽样，这个函数会返回一个随机值。</span>
<span class="token comment">// 以下的语句返回的值会不相同</span>
hive<span class="token operator">></span> <span class="token constant">SELECT</span> <span class="token operator">*</span> from numbers <span class="token function">TABLESAMPLE</span><span class="token punctuation">(</span><span class="token constant">BUCKET</span> <span class="token number">3</span> <span class="token constant">OUT</span> <span class="token constant">OF</span> <span class="token number">10</span> <span class="token class-name">ON</span> <span class="token function">rand</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> s<span class="token punctuation">;</span>
hive<span class="token operator">></span> <span class="token constant">SELECT</span> <span class="token operator">*</span> from numbers <span class="token function">TABLESAMPLE</span><span class="token punctuation">(</span><span class="token constant">BUCKET</span> <span class="token number">3</span> <span class="token constant">OUT</span> <span class="token constant">OF</span> <span class="token number">10</span> <span class="token class-name">ON</span> <span class="token function">rand</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> s<span class="token punctuation">;</span>
hive<span class="token operator">></span> <span class="token constant">SELECT</span> <span class="token operator">*</span> from numbers <span class="token function">TABLESAMPLE</span><span class="token punctuation">(</span><span class="token constant">BUCKET</span> <span class="token number">3</span> <span class="token constant">OUT</span> <span class="token constant">OF</span> <span class="token number">10</span> <span class="token class-name">ON</span> <span class="token function">rand</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> s<span class="token punctuation">;</span>

<span class="token comment">// 如果按照指定的列而不是rand()函数进行分桶，同一语句多次执行的返回值是相同的</span>
hive<span class="token operator">></span> <span class="token constant">SELECT</span> <span class="token operator">*</span> from numbers <span class="token function">TABLESAMPLE</span><span class="token punctuation">(</span><span class="token constant">BUCKET</span> <span class="token number">3</span> <span class="token constant">OUT</span> <span class="token constant">OF</span> <span class="token number">10</span> <span class="token class-name">ON</span> number<span class="token punctuation">)</span> s<span class="token punctuation">;</span>
hive<span class="token operator">></span> <span class="token constant">SELECT</span> <span class="token operator">*</span> from numbers <span class="token function">TABLESAMPLE</span><span class="token punctuation">(</span><span class="token constant">BUCKET</span> <span class="token number">5</span> <span class="token constant">OUT</span> <span class="token constant">OF</span> <span class="token number">10</span> <span class="token class-name">ON</span> number<span class="token punctuation">)</span> s<span class="token punctuation">;</span>
hive<span class="token operator">></span> <span class="token constant">SELECT</span> <span class="token operator">*</span> from numbers <span class="token function">TABLESAMPLE</span><span class="token punctuation">(</span><span class="token constant">BUCKET</span> <span class="token number">3</span> <span class="token constant">OUT</span> <span class="token constant">OF</span> <span class="token number">10</span> <span class="token class-name">ON</span> number<span class="token punctuation">)</span> s<span class="token punctuation">;</span>   

<span class="token comment">// 分桶语句中的分母表示的是数据将会被散列的桶的个数?，而分子表示将会选择的桶的个数：</span>
hive<span class="token operator">></span> <span class="token constant">SELECT</span> <span class="token operator">*</span> from numbers <span class="token function">TABLESAMPLE</span><span class="token punctuation">(</span><span class="token constant">BUCKET</span> <span class="token number">1</span> <span class="token constant">OUT</span> <span class="token constant">OF</span> <span class="token number">2</span> <span class="token class-name">ON</span> number<span class="token punctuation">)</span> s<span class="token punctuation">;</span>
hive<span class="token operator">></span> <span class="token constant">SELECT</span> <span class="token operator">*</span> from numbers <span class="token function">TABLESAMPLE</span><span class="token punctuation">(</span><span class="token constant">BUCKET</span> <span class="token number">2</span> <span class="token constant">OUT</span> <span class="token constant">OF</span> <span class="token number">2</span> <span class="token class-name">ON</span> number<span class="token punctuation">)</span> s<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h1 id="三、数据块抽样" tabindex="-1"><a class="header-anchor" href="#三、数据块抽样" aria-hidden="true">#</a> 三、数据块抽样</h1>
<p>​		Hive 提供了另一种按照抽样百分比进行抽样的方式，这种是基于行数的，按照输入路径下的数据块百分比进行抽样：</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code>hive<span class="token operator">></span> <span class="token constant">SELECT</span> <span class="token operator">*</span> from numbersflat <span class="token function">TABLESAMPLE</span><span class="token punctuation">(</span><span class="token number">0.1</span> <span class="token operator">*</span> <span class="token constant">PERCENT</span><span class="token punctuation">)</span> s<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>注：这种抽样方式不一定适用于所有的文件格式。</p>
<h1 id="四、union-all" tabindex="-1"><a class="header-anchor" href="#四、union-all" aria-hidden="true">#</a> 四、UNION ALL</h1>
<p>​		UNION ALL 可以将 2个或多个表进行合并。</p>
<p>​		每一个 union 子查询都必须具有相同的列，而且对应的每个字段的字段类型必须是一致的。</p>
</div></template>


